# Generated by Django 5.2.6 on 2025-11-05 07:56

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='位置名称')),
                ('description', models.TextField(verbose_name='位置説明')),
                ('x_position', models.IntegerField(default=0, verbose_name='X座標')),
                ('y_position', models.IntegerField(default=0, verbose_name='Y座標')),
                ('width', models.IntegerField(default=180, verbose_name='幅')),
                ('height', models.IntegerField(default=80, verbose_name='高さ')),
                ('background_color', models.CharField(default='#ffffff', max_length=20, verbose_name='背景色')),
                ('border_color', models.CharField(default='#dee2e6', max_length=20, verbose_name='枠色')),
                ('allowed_block_types', models.JSONField(default=list, verbose_name='許可される積木タイプ')),
                ('required', models.BooleanField(default=False, verbose_name='必須')),
                ('order', models.IntegerField(default=0, verbose_name='表示順序')),
            ],
            options={
                'verbose_name': 'アーキテクチャスロット',
                'verbose_name_plural': 'アーキテクチャスロット',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BuildingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='積木名称')),
                ('block_type', models.CharField(choices=[('data_model', 'データモデル積木'), ('view', 'ビュー積木'), ('template', 'テンプレート積木'), ('url', 'URL設定積木'), ('admin', '管理画面積木')], max_length=20, verbose_name='積木タイプ')),
                ('description', models.TextField(verbose_name='積木説明')),
                ('code_snippet', models.TextField(verbose_name='コードスニペット')),
                ('color', models.CharField(choices=[('#4C56B3', '青色 - Django基礎'), ('#FF6B6B', '赤色 - Python基礎'), ('#4CAF50', '緑色 - データモデル'), ('#2196F3', '青色 - データベース'), ('#FF9800', '橙色 - 管理画面')], default='#4CAF50', max_length=20, verbose_name='積木カラー')),
                ('order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('expand_knowledge', models.TextField(blank=True, verbose_name='知識拓展')),
                ('usage_examples', models.TextField(blank=True, verbose_name='使用例')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '積木モジュール',
                'verbose_name_plural': '積木モジュール',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='チャプタータイトル')),
                ('description', models.TextField(verbose_name='チャプター説明')),
                ('order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '学習チャプター',
                'verbose_name_plural': '学習チャプター',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArchitectureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板说明')),
                ('slot_configurations', models.JSONField(default=dict, verbose_name='插槽配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_blocks', models.ManyToManyField(blank=True, to='tutorial.buildingblock', verbose_name='推荐积木')),
            ],
            options={
                'verbose_name': '架构模板',
                'verbose_name_plural': '架构模板',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='buildingblock',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='building_blocks', to='tutorial.chapter', verbose_name='所属チャプター'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('fill', '穴埋め問題（単一空）'), ('multi_fill', '穴埋め問題（複数空）'), ('choice', '選択問題')], max_length=10, verbose_name='問題タイプ')),
                ('question_text', models.TextField(verbose_name='問題文')),
                ('code_snippet', models.TextField(blank=True, null=True, verbose_name='コードスニペット')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('explanation', models.TextField(blank=True, verbose_name='解説')),
                ('hint', models.TextField(blank=True, verbose_name='ヒント')),
                ('difficulty', models.CharField(choices=[('easy', '簡単'), ('medium', '普通'), ('hard', '難しい')], default='medium', max_length=10, verbose_name='難易度')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.chapter', verbose_name='所属チャプター')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='選択肢／答え')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解かどうか')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('blank_index', models.IntegerField(default=0, verbose_name='空欄番号')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.question', verbose_name='関連する問題')),
            ],
            options={
                'verbose_name': '選択肢／解答',
                'verbose_name_plural': '選択肢／解答',
                'ordering': ['blank_index', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudyGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField(verbose_name='学習内容')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開状態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorial.chapter', verbose_name='所属チャプター')),
            ],
            options={
                'verbose_name': '学習ガイド',
                'verbose_name_plural': '学習ガイド',
            },
        ),
        migrations.CreateModel(
            name='UserArchitecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='マイアーキテクチャ図', max_length=100, verbose_name='アーキテクチャ図名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('slot_assignments', models.JSONField(default=dict, verbose_name='スロット割り当て')),
                ('generated_code', models.TextField(blank=True, verbose_name='生成コード')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザーアーキテクチャ図',
                'verbose_name_plural': 'ユーザーアーキテクチャ図',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0, verbose_name='経験値')),
                ('level', models.IntegerField(default=1, verbose_name='レベル')),
                ('total_chapters_completed', models.IntegerField(default=0, verbose_name='完了章数')),
                ('chapters_with_experience', models.TextField(blank=True, default='', verbose_name='経験値獲得済み章')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザープロファイル',
                'verbose_name_plural': 'ユーザープロファイル',
            },
        ),
        migrations.CreateModel(
            name='WrongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_answer', models.TextField(verbose_name='間違った回答')),
                ('correct_answer', models.TextField(verbose_name='正しい回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録時間')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.question', verbose_name='問題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '間違い記録',
                'verbose_name_plural': '間違い記録',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='完了済みかどうか')),
                ('score', models.IntegerField(default=0, verbose_name='スコア')),
                ('studied_guide', models.BooleanField(default=False, verbose_name='学習ガイドを学習済み')),
                ('experience_awarded', models.BooleanField(default=False, verbose_name='経験値獲得済みかどうか')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.chapter', verbose_name='チャプター')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザー進捗',
                'verbose_name_plural': 'ユーザー進捗',
                'unique_together': {('user', 'chapter')},
            },
        ),
    ]
