# Generated by Django 5.2.6 on 2025-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingblock',
            name='manually_unlocked',
            field=models.BooleanField(default=False, verbose_name='手动解锁（忽略章节要求）'),
        ),
    ]
