# Generated by Django 5.2.6 on 2025-11-06 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_buildingblock_manually_unlocked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='徽章名称')),
                ('description', models.TextField(verbose_name='徽章描述')),
                ('badge_type', models.CharField(choices=[('level', '等级徽章'), ('achievement', '成就徽章'), ('special', '特殊徽章')], default='achievement', max_length=20, verbose_name='徽章类型')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#4CAF50', max_length=20, verbose_name='徽章颜色')),
                ('required_experience', models.IntegerField(default=0, verbose_name='所需经验值')),
                ('required_level', models.IntegerField(default=0, verbose_name='所需等级')),
                ('required_chapters', models.IntegerField(default=0, verbose_name='所需完成章节数')),
                ('order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '徽章',
                'verbose_name_plural': '徽章',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.badge', verbose_name='徽章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户徽章',
                'verbose_name_plural': '用户徽章',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
