# Generated by Django 5.2.6 on 2025-11-14 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_badge_userbadge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterStudyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='学習開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='学習終了時間')),
                ('total_seconds', models.IntegerField(default=0, verbose_name='総学習時間（秒）')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.chapter', verbose_name='チャプター')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '学習時間記録',
                'verbose_name_plural': '学習時間記録',
                'ordering': ['-start_time'],
            },
        ),
    ]
