# Generated by Django 5.2.6 on 2025-11-14 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_chapterstudytime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architecturetemplate',
            options={'ordering': ['order'], 'verbose_name': 'アーキテクチャテンプレート', 'verbose_name_plural': 'アーキテクチャテンプレート'},
        ),
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['order'], 'verbose_name': 'バッジ', 'verbose_name_plural': 'バッジ'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-unlocked_at'], 'verbose_name': 'ユーザーバッジ', 'verbose_name_plural': 'ユーザーバッジ'},
        ),
        migrations.AlterField(
            model_name='architecturetemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='テンプレート説明'),
        ),
        migrations.AlterField(
            model_name='architecturetemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='architecturetemplate',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='デフォルトテンプレートかどうか'),
        ),
        migrations.AlterField(
            model_name='architecturetemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='テンプレート名称'),
        ),
        migrations.AlterField(
            model_name='architecturetemplate',
            name='order',
            field=models.IntegerField(default=0, verbose_name='順序'),
        ),
        migrations.AlterField(
            model_name='architecturetemplate',
            name='recommended_blocks',
            field=models.ManyToManyField(blank=True, to='tutorial.buildingblock', verbose_name='推奨積木'),
        ),
        migrations.AlterField(
            model_name='architecturetemplate',
            name='slot_configurations',
            field=models.JSONField(default=dict, verbose_name='スロット設定'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('level', 'レベルバッジ'), ('achievement', '実績バッジ'), ('special', '特殊バッジ')], default='achievement', max_length=20, verbose_name='バッジタイプ'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='color',
            field=models.CharField(default='#4CAF50', max_length=20, verbose_name='バッジカラー'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(verbose_name='バッジ説明'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='🏆', max_length=50, verbose_name='アイコン'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100, verbose_name='バッジ名称'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='order',
            field=models.IntegerField(default=0, verbose_name='表示順序'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='required_chapters',
            field=models.IntegerField(default=0, verbose_name='必要完了チャプター数'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='required_experience',
            field=models.IntegerField(default=0, verbose_name='必要経験値'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='required_level',
            field=models.IntegerField(default=0, verbose_name='必要レベル'),
        ),
        migrations.AlterField(
            model_name='buildingblock',
            name='expand_knowledge',
            field=models.TextField(blank=True, verbose_name='知識拡張'),
        ),
        migrations.AlterField(
            model_name='buildingblock',
            name='manually_unlocked',
            field=models.BooleanField(default=False, verbose_name='手動アンロック（チャプター要求を無視）'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.badge', verbose_name='バッジ'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='unlocked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='獲得時間'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
