# Generated by Django 5.2.6 on 2025-11-17 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_alter_architecturetemplate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chapterstudytime',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('user', 'chapter'), name='unique_active_session_per_user_chapter'),
        ),
    ]
