# Generated by Django 5.2.6 on 2025-11-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_chapterstudytime_unique_active_session_per_user_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectureslot',
            name='layer_type',
            field=models.CharField(choices=[('http', 'HTTP層'), ('url', 'URLルーティング層'), ('view', 'ビューレイヤー'), ('form', 'フォーム層'), ('model', 'モデル層'), ('template', 'テンプレート層')], default='view', max_length=20, verbose_name='レイヤータイプ'),
        ),
        migrations.AlterField(
            model_name='architectureslot',
            name='height',
            field=models.IntegerField(default=120, verbose_name='高さ'),
        ),
        migrations.AlterField(
            model_name='architectureslot',
            name='width',
            field=models.IntegerField(default=200, verbose_name='幅'),
        ),
        migrations.AlterField(
            model_name='buildingblock',
            name='block_type',
            field=models.CharField(choices=[('data_model', 'データモデル積木'), ('view', 'ビュー積木'), ('template', 'テンプレート積木'), ('url', 'URL設定積木'), ('admin', '管理画面積木'), ('form', 'フォーム積木')], max_length=20, verbose_name='積木タイプ'),
        ),
        migrations.AlterField(
            model_name='buildingblock',
            name='color',
            field=models.CharField(choices=[('#4C56B3', '青色 - ビュー'), ('#FF6B6B', '赤色 - テンプレート'), ('#4CAF50', '緑色 - URL設定'), ('#2196F3', '青色 - 管理画面'), ('#FF9800', '橙色 - フォーム'), ('#9ED877', '橙色 - データモデル')], default='#4CAF50', max_length=20, verbose_name='積木カラー'),
        ),
    ]
