# Generated by Django 5.2.6 on 2025-11-17 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_architectureslot_layer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='標準アーキテクチャ図', max_length=100, verbose_name='アーキテクチャ図名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_default', models.BooleanField(default=True, verbose_name='デフォルト図')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'アーキテクチャ図',
                'verbose_name_plural': 'アーキテクチャ図',
            },
        ),
        migrations.CreateModel(
            name='DiagramLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_type', models.CharField(choices=[('url', 'URLルーティング層'), ('view', 'ビューレイヤー'), ('form', 'フォーム層'), ('model', 'モデル層'), ('template', 'テンプレート層')], max_length=20, verbose_name='レイヤータイプ')),
                ('name', models.CharField(max_length=100, verbose_name='レイヤー名')),
                ('description', models.TextField(verbose_name='レイヤー説明')),
                ('order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('diagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.architecturediagram', verbose_name='所属アーキテクチャ図')),
            ],
            options={
                'verbose_name': 'アーキテクチャレイヤー',
                'verbose_name_plural': 'アーキテクチャレイヤー',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DiagramComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='コンポーネント名')),
                ('description', models.TextField(verbose_name='コンポーネント説明')),
                ('component_type', models.CharField(max_length=50, verbose_name='コンポーネントタイプ')),
                ('position_data', models.JSONField(default=dict, verbose_name='位置データ')),
                ('allowed_block_types', models.JSONField(default=list, verbose_name='許可される積木タイプ')),
                ('order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.diagramlayer', verbose_name='所属レイヤー')),
            ],
            options={
                'verbose_name': 'アーキテクチャコンポーネント',
                'verbose_name_plural': 'アーキテクチャコンポーネント',
                'ordering': ['order'],
            },
        ),
    ]
