# Generated by Django 5.2.6 on 2025-11-18 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_architecturediagram_diagramlayer_diagramcomponent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureDiagramTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('layers', models.JSONField(default=list, verbose_name='层级配置')),
                ('connections', models.JSONField(default=list, verbose_name='连接配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模板')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '架构图模板',
                'verbose_name_plural': '架构图模板',
            },
        ),
        migrations.AlterModelOptions(
            name='architecturediagram',
            options={'verbose_name': '架构图', 'verbose_name_plural': '架构图'},
        ),
        migrations.AlterModelOptions(
            name='diagramcomponent',
            options={'ordering': ['layer', 'order'], 'verbose_name': '架构图组件', 'verbose_name_plural': '架构图组件'},
        ),
        migrations.RemoveField(
            model_name='architecturediagram',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='architecturediagram',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='diagramcomponent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='diagramcomponent',
            name='position_data',
        ),
        migrations.AddField(
            model_name='architecturediagram',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='是否为模板'),
        ),
        migrations.AddField(
            model_name='architecturediagram',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='diagramcomponent',
            name='color',
            field=models.CharField(default='#4C56B3', max_length=20, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='diagramcomponent',
            name='height',
            field=models.IntegerField(default=80, verbose_name='高度'),
        ),
        migrations.AddField(
            model_name='diagramcomponent',
            name='position_x',
            field=models.IntegerField(default=0, verbose_name='X坐标'),
        ),
        migrations.AddField(
            model_name='diagramcomponent',
            name='position_y',
            field=models.IntegerField(default=0, verbose_name='Y坐标'),
        ),
        migrations.AddField(
            model_name='diagramcomponent',
            name='width',
            field=models.IntegerField(default=200, verbose_name='宽度'),
        ),
        migrations.AlterField(
            model_name='architecturediagram',
            name='description',
            field=models.TextField(blank=True, verbose_name='架构图描述'),
        ),
        migrations.AlterField(
            model_name='architecturediagram',
            name='name',
            field=models.CharField(max_length=100, verbose_name='架构图名称'),
        ),
        migrations.AlterField(
            model_name='diagramcomponent',
            name='allowed_block_types',
            field=models.JSONField(default=list, verbose_name='允许的积木类型'),
        ),
        migrations.AlterField(
            model_name='diagramcomponent',
            name='component_type',
            field=models.CharField(max_length=50, verbose_name='组件类型'),
        ),
        migrations.AlterField(
            model_name='diagramcomponent',
            name='layer',
            field=models.CharField(max_length=50, verbose_name='所属层级'),
        ),
        migrations.AlterField(
            model_name='diagramcomponent',
            name='name',
            field=models.CharField(max_length=100, verbose_name='组件名称'),
        ),
        migrations.AlterField(
            model_name='diagramcomponent',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='diagramcomponent',
            name='diagram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutorial.architecturediagramtemplate', verbose_name='所属架构图'),
            preserve_default=False,
        ),
    ]
