# Generated by Django 5.2.6 on 2025-11-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0009_architecturediagramtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyguide',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='study_guide_zips/', verbose_name='添付ZIPファイル'),
        ),
    ]
