# Generated by Django 5.2.6 on 2025-11-22 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0010_studyguide_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyguide',
            name='attachment',
        ),
        migrations.CreateModel(
            name='StudyGuideAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='プレースホルダキー（例：ZIP1）')),
                ('file', models.FileField(upload_to='study_guide_zips/', verbose_name='添付ファイル（ZIPなど）')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='リンク表示名（例：サンプルコードZIP）')),
                ('study_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tutorial.studyguide', verbose_name='対象学習ガイド')),
            ],
            options={
                'verbose_name': '学習ガイド添付',
                'verbose_name_plural': '学習ガイド添付',
            },
        ),
    ]
