# Generated by Django 5.2.6 on 2025-11-26 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0011_remove_studyguide_attachment_studyguideattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingblock',
            name='block_type',
            field=models.CharField(choices=[('data_model', 'データモデル積木'), ('view', 'ビュー積木'), ('template', 'テンプレート積木'), ('url', 'URL設定積木'), ('admin', '管理画面積木'), ('form', 'フォーム積木'), ('database', 'データベース積木')], max_length=20, verbose_name='積木タイプ'),
        ),
        migrations.AlterField(
            model_name='buildingblock',
            name='color',
            field=models.CharField(choices=[('#4C56B3', '青色 - ビュー'), ('#FF6B6B', '赤色 - テンプレート'), ('#4CAF50', '緑色 - URL設定'), ('#2196F3', '青色 - 管理画面'), ('#FF9800', '橙色 - フォーム'), ('#9ED877', '橙色 - データモデル'), ('#795548', '茶色 - データベース')], default='#4CAF50', max_length=20, verbose_name='積木カラー'),
        ),
        migrations.CreateModel(
            name='ChapterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.IntegerField(verbose_name='正解数')),
                ('total_count', models.IntegerField(verbose_name='問題総数')),
                ('accuracy', models.FloatField(verbose_name='正答率（%）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.chapter', verbose_name='チャプター')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'チャプター結果',
                'verbose_name_plural': 'チャプター結果',
                'ordering': ['-created_at'],
            },
        ),
    ]
