# Generated by Django 5.2.6 on 2025-12-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0013_userquestionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='required_score',
            field=models.IntegerField(default=0, help_text='任意のチャプターでこの点数以上を獲得すると条件達成とみなす', verbose_name='必要スコア'),
        ),
    ]
